### ISSUE TITLE
Event confirmation mails stay Unread

### ISSUE THREAD

**Issue by be-neth** [1stsetup/exchangecalendar#14]
When receiving event, or mail for event confirmation, the mail seems to stay unread in thunderbird folder.
Event if i delete the mail, the "deleted Items" folder shows that i have 1 unread mail...

Is this related to exchange plugin ?

**Comment by 1stsetup** [comment]
This is a problem of Thunderbird. The Exchange calendar add-on does nothing with the email.
It could also be the Lightning add-on because it delivers the so called iTIP buttons (Accept/Tentative/Cancel)
