### ISSUE TITLE
Error when pressing "Check server and mailbox"

### ISSUE THREAD

**Issue by silverclaw** [1stsetup/exchangecalendar#5]
When creating an exchange calendar, after inserting the manual server address, email and username, we are supposed to click the "Check server and mailbox" button. Nothing happens (and the button becomes disabled). The log says:

1st-setup: Error: Warning: Error during creation of erPrimarySMTPCheckRequest. Err=TypeError: can't wrap XML objects

**Comment by 1stsetup** [comment]
Please read bug https://www.1st-setup.nl/bugzilla/show_bug.cgi?id=132.

**Comment by silverclaw** [comment]
Yeah, I'm using the GIT version as documented here http://www.1st-setup.nl/wordpress/?page_id=413 and get that error
